config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get '/about', to: 'pages#about'
  # resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  resources :articles # all the restful routes for our articles resources
  get 'signup', to: 'users#new'
  # post 'users', to: 'users#createeeee'
  resources :users, except: [:new]

  #login route
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/user.rb
class User < ApplicationRecord
    before_save {self.email = email.downcase}
    has_many :articles, dependent: :destroy
    REGEX_PATTERN = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :username, presence: true,
                         uniqueness: { case_sensitive: false },
                         length: {minimum: 3, maximum: 25}
    validates :email, presence: true,
                      length: {maximum: 105},
                      format: { with: REGEX_PATTERN}
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
      if session[:user_id]
          @current_user ||= User.find(session[:user_id])
      end
  end

  def logged_in?
      !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 4)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    # @article.user = User.find(session[:user_id])
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = 'Article was updated succesfully'
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description)
    end

    def require_same_user
      if current_user != @article.user && !current_user.admin?
        flash[:alert] = "You can editt or delete your own article"
        redirect_to @article
      end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end

    def about
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        # byebug
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Logged in succesfully"
            redirect_to user
        else
            flash.now[:alert] = "There was something wrong with your login details"  
            render 'new'
        end
    end 


    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged out"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:edit, :update]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def index
        @users = User.all.paginate(page: params[:page], per_page: 3)
    end

    def show
        @articles = @user.articles.paginate(page: params[:page], per_page: 4)
    end

    def new
        @user = User.new
    end

    def edit
    end

    def update
        if @user.update(user_params)
            flash[:notice] = "Your account informationw as successfuly updated"
            redirect_to @user
        else
            render 'edit'
        end
    end

    def destroy
      @user.destroy
      session[:user_id] = nil if @user == current_user
      flash[:notice] = "Account and all associated articles successfully deleted"
      redirect_to articles_path
    end

    def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have successfully signed up"
        redirect_to articles_path
      else
        render 'new'
      end
    end

    private
        def user_params
            params.require(:user).permit(:username, :email, :password)
        end

        def set_user
            @user = User.find(params[:id])
        end

        def require_same_user
          if current_user != @user && !current_user.admin?
            flash[:alert] = "You can only edit your own account"
            redirect_to @user
          end
        end


end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, options = {size: 80})
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        image_src = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(image_src, alt: user.username, class: "rounded shadow mx-auto d-block")
    end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_articles.html.erb
  <h1 class="text-center mt-4">Articles Listing page</h1>
  <div class="container">
    <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4 ">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header">
            <% if article.user %>
                by <%= link_to article.user.username, user_path(article.user) %>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"> <%= article.title %></h5>
            <p class="card-text"><%= article.description %></p>
            <%= link_to "Show", article, class: 'btn btn-outline-primary' %>
            <% if logged_in? && (article.user == current_user || current_user.admin?)%>
              <%= link_to "Edit", edit_article_path(article), class: 'btn btn-outline-success' %>
              <%= link_to "Delete", article, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-outline-danger' %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %>, Edited <%= time_ago_in_words(article.created_at) %> </small>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>

<%= link_to  "Create new Article",  new_article_path, class: "text-center d-block mx-auto" %>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
    <%= render  "shared/errors", obj: @article %>
      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing all articles</h1>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>
<%= render  "articles" %>
<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a new article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
  <h1 class="text-center mt-4">Articles Listing page</h1>
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4 ">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header">
          <% if @article.user %>
            by <%= @article.user.username%>
            <%= link_to gravatar_for(@article.user, size: 100), user_path(@article.user) %>
          <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"> <%= simple_format(@article.title) %></h5>
            <p class="card-text"><%= simple_format(@article.description) %></p>
            <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
            <%= link_to  "Edit Article", edit_article_path(@article), class: 'btn btn-outline-primary' %>
            <%= link_to  "Delete", article_path(@article), method: :delete, data: {confirm: 'Are you sure?'} , class: 'btn btn-outline-danger' %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(@article.created_at) %>, Edited <%= time_ago_in_words(@article.created_at) %> </small>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='d-flex flex-column'>
    <%= render 'layouts/partials/navigation' %>
    <div id="page-content">
      <%= render 'layouts/partials/message' %>
      <%= yield %>
    </div>
    <%= render  "layouts/partials/footer" %>
  </body>
</html>

app/views/layouts/partials/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
    <div class="container text-center">
      <small>Copyright &copy; Your Website</small>
    </div>
</footer>

app/views/layouts/partials/_message.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
    <%= msg %>
  </div>
<% end %>

app/views/layouts/partials/_navigation.html.erb
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to  "ALPHA BLOC", root_path, class: 'navbar-brand', id: 'logo' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to  "Bloggers", users_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Articles
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% if logged_in? %>
                <%= link_to  "Create new article", new_article_path, class: 'dropdown-item' %>
              <% end %>
              <%= link_to  "View Articles", articles_path, class: 'dropdown-item'%>
            </div>
          </li>
          <% if logged_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to  "View your profile", current_user, class: 'dropdown-item' %>
                <%= link_to  "Edit your profile", edit_user_path(current_user), class: 'dropdown-item'%>
                <%= link_to  "Delete your profile", user_path(current_user), class: 'dropdown-item text-danger', method: :delete, data: {confirm: "Are you sure?"} %>
              </div>
            </li>
            <li class="nav-item">
              <%= link_to  "Logout", logout_path, class: "nav-link", method: :delete %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to  "Login", login_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to  "Signup", signup_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

app/views/pages/about.html.erb
<h1>Welcome to the about page</h1>

<h1>Welcome to the home page</h1>
<%= link_to  "Articles listing", articles_path %>
<%= link_to  "Home Page", root_path %>

app/views/pages/home.html.erb
  <div class="container" id="home-container">
      <div class="jumbotron text-center text-white">
          <h1 class="display-4">Alpha Blog</h1>
          <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
          <hr class="my-4">
          <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
          <p class="lead">
              <%= link_to  "Sign Up", signup_path, class: "btn btn-success btn-lg" %>
          </p>
      </div>
  </div>

app/views/shared/_errors.html.erb
  <% if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h2>The following errors prevented the <%= obj.class.name.downcase %> from being saved</h2>
        <ul>
          <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  <% end %>

app/views/users/_signup_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render  "shared/errors", obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :username, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Name" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.text_field :email, rows: 10, class: "form-control shadow rounded", placeholder: "example_email@email.com" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :password, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.password_field :password, rows: 10, class: "form-control shadow rounded", placeholder: "password" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit(@user.new_record? ? "Sign Up" : "Update", class: "btn btn-outline-light btn-lg") %>
        </div>
      <% end %>
    </div>
    <%= link_to '[ Cancel and return to articles listing ]', root_path, class: "text-info" %>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>
<%= render 'signup_form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Bloggers</h1>
  <div class="container">
  <div class="flickr_pagination mb-4">
    <%= will_paginate @users, :container => false %>
  </div>
    <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4 ">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header">
            <%= link_to  user.username, user_path(user) %>
          </div>
          <div class="card-body">
            <h5 class="card-title"> <%= link_to gravatar_for(user, size:150), user %></h5>
            <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
            <%= link_to  "View Profile", user, class: 'btn btn-outline-success' %>
            <% if logged_in? %>
            <% if user == current_user %>
              <%= link_to  "Edit Profile", edit_user_path(user), class: 'btn btn-outline-primary' %>
            <% end %>
            <% if current_user.admin? %>
              <%= link_to  "Delete Profile", user_path(user), class: 'btn btn-outline-primary', method: :delete,
              data: {confirm: "Are you sure you want to delete the user account and all associated articles?"} %>
            <% end %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Join <%= time_ago_in_words(user.created_at) %></small>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    <div class="flickr_pagination mb-4">
      <%= will_paginate @users, :container => false %>
    </div>
  </div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Create a new article</h1>
<%= render 'signup_form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>
 <%= gravatar_for @user, {size: 200} %>

<div class="text-center mt-4">
  <% if logged_in? && @user == current_user %>
    <%= link_to  "Edit your Profile", edit_user_path(@user), class: "btn btn-outline-primary" %>
  <% end %>
</div>

 <h3 class="text-center mt-4">Articles </h3>
 <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>
<%= render  "articles/articles" %>
<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>